---
title: "Mixed Python and R Code Example"
format: 
  dashboard:
    orientation: columns
    cold-fold: true
---

## Column -- Python {width=50%}

### Row -- Python Data {height="30%"}

```{python}
#| title: Python Example
import seaborn as sns
geyser = sns.load_dataset("geyser")
geyser.head()
```

### Row -- Python Plot {height="70%"}

```{python}
import matplotlib.pyplot as plt
sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.scatterplot(data=geyser, x="duration", y="waiting", hue="kind",
                s=200, alpha=0.75)
plt.title("Geyser Eruptions (Python)")
plt.show()
```

## Column -- R {width="50%"}

### Row -- R Data {height="30%"}

```{r}
#| title: R Example
library(ggplot2)
geyser <- faithful |>
  dplyr::rename(duration = "eruptions") |>
  dplyr::mutate(kind = c("short","long")[1 + (waiting > 67)])
head(geyser, n = 5)
```

### Row -- R Plot {height="70%"}

```{r}
ggplot(geyser, aes(x = duration, y = waiting, fill = kind)) +
  geom_point(size=5, alpha=0.75, color = "white", shape=21) +
  ggtitle("Geyser Eruptions (R)") +
  theme_minimal()
```
