name: Deploy Shinylive App

on:
  push:
    branches: [main, master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Shinylive
        run: |
          Rscript -e "install.packages('shinylive')"

      - name: Export Shinylive App
        run: |
          cp -r R inst/connect_modules/
          Rscript -e "shinylive::export('inst/connect_modules', 'docs/shiny', wasm_packages = FALSE)"

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Shinylive Quarto Extension
        run: |
          quarto add quarto-ext/shinylive --no-prompt

      - name: Render Shinylive Dashboard
        run: |
          quarto render docs/demo_shinylive.qmd

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
